"""add billing adjustments

Revision ID: 6f5d232a275d
Revises: a8d4e6f1c2b3
Create Date: 2026-10-08 09:59:44.508765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '6f5d232a275d'
down_revision: Union[str, None] = 'a8d4e6f1c2b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

plan_name = postgresql.ENUM(
    "free",
    "pro",
    name="plan_name",
    create_type=False,
)

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing_adjustments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.Column('source_event_id', sa.Text(), nullable=False),
    sa.Column("old_plan", plan_name, nullable=False),
    sa.Column("new_plan", plan_name, nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('old_monthly_price_microusd', sa.BigInteger(), nullable=False),
    sa.Column('new_monthly_price_microusd', sa.BigInteger(), nullable=False),
    sa.Column('amount_microusd', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='usd', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_event_id')
    )
    op.create_index(op.f('ix_billing_adjustments_invoice_id'), 'billing_adjustments', ['invoice_id'], unique=False)
    op.create_index('ix_billing_adjustments_tenant_period', 'billing_adjustments', ['tenant_id', 'period_start'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_billing_adjustments_tenant_period', table_name='billing_adjustments')
    op.drop_index(op.f('ix_billing_adjustments_invoice_id'), table_name='billing_adjustments')
    op.drop_table('billing_adjustments')
    # ### end Alembic commands ###