"""track stripe event ordering

Revision ID: baa2a53554f2
Revises: e5ca33e8ba3d
Create Date: 2026-09-30 20:49:24.485746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'baa2a53554f2'
down_revision: Union[str, None] = 'e5ca33e8ba3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
    "subscriptions",
    sa.Column(
        "last_stripe_event_created",
        sa.BigInteger(),
        server_default="0",
        nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'last_stripe_event_created')
    # ### end Alembic commands ###
